config/routes.rb
Rails.application.routes.draw do
  

  

  devise_for :users
  resources :movies do
   collection do
     get 'search'
    end 
  resources :reviews, except: [:show, :index] do
    member do
    get 'approve'
    end
  end
    
    resources :similarities, except: [:show, :index]
  end 

  resources :links do
    member do
      put "like", to: "similarities#upvote"
      put "dislike", to: "similarities#downvote" 
    end
  end    
  

  get 'pages/about'

  get 'pages/contact'

  get 'pages/privacy'
  
  root 'movies#index'
  
  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]


  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end  
  end  

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.order("year DESC").paginate(:page => params[:page], :per_page => 12)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  @movie = Movie.find_by_permalink(params[:id])
  @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
   if @reviews.blank?
    @avg_rating = 0
   else  
  @avg_rating = @reviews.average(:rating).round(2)
   end
   @similarities = Similarity.where(movie_id: @movie.id).order("created_at DESC")
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find_by_permalink(params[:id])
    end

    def check_user
      unless current_user.admin?
         redirect_to root_url, alert: "Sorry, only admins can do that!"
      end   
    end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :actor, :description, :picture, :raiting, :genre, :url)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => { multipart: true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year %><br>
    <%= f.text_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :actor %><br>
    <%= f.text_field :actor, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :picture %><br>
    <%= f.file_field :picture, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :raiting %><br>
    <%= f.text_field :raiting, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :genre %><br>
    <%= f.text_field :genre, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie, class: "btn btn-link" %> |
<%= link_to 'Back', movies_path, class: "btn btn-link" %>

app/views/movies/index.html.erb
<div class="jumbotron">
  <h2> What's the movie about?</h2>
  <p> Explore your favorite or currently showing in theater movies. <br>
    Leave reviews and ratings for fellow movie lovers! <br>
    And VOTE for similar movies. </p>
  </div>
  <div class="center">
    <div class="row">
      <% @movies.each do |movie| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <div class="thumbnail">
         
          <%= link_to (image_tag movie.picture_url), movie %>

          <div class="caption">
            <h4><%= link_to movie.title, movie  %></h4>
            <p>
              <% if user_signed_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-link" %>
              <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
              <% end %> 
            </p>
          </div>
        </div>
      </div>  

      <% end %>
    </div>
  </div>

  <br>
  <%= will_paginate @movies, renderer: BootstrapPagination::Rails %>
  <br>
  <% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Movie', new_movie_path, class: "btn btn-link" %>
  <% end %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path, class: "btn btn-link" %>

app/views/movies/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Actor</th>
      <th>Genre</th>
     <% if user_signed_in? && current_user.admin? %>
      <th colspan="2"></th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie %></td>
        <td><%= movie.year %></td>
        <td><%= movie.actor %></td>
        <td><%= movie.genre %></td>
       <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
       <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="movieimage img-thumbnail img-responsive">
      <%= image_tag(@movie.picture_url) if @movie.picture.present? %>


      <!-- Button trigger modal to watch  trailer -->
      <div class="blocktrailer">
        <button type="button" class="playtrailer" data-trailer-youtube-id="<%= @movie.url %>" data-toggle="modal" data-target="#trailer">

        </button>
      </div>
    </div>
  </div>
  
  <div class="col-md-9">
    <p>
      <strong>Title:</strong>
      <%= @movie.title %>
    </p>
    
    <p>
      <strong>Year:</strong>
      <%= @movie.year %>
    </p>

    <p>
      <strong>Stars:</strong>
      <%= @movie.actor %>
    </p>
    
    <p>
      <strong>Description:</strong>
      <%= @movie.description %>
    </p>
    

    <p>
      <strong>IMDB Rating:</strong>
      <%= @movie.raiting %>
    </p>

    <p>
      <strong>Genre:</strong>
      <%= @movie.genre %>
    </p>


    

    <!-- Modal for movie trailer -->
    <div class="modal" id="trailer">
      <div class="modal-dialog">
        <div class="modal-content">
          <a href="#" class="hanging-close" data-dismiss="modal" aria-hidden="true">
            <img src="https://lh5.ggpht.com/v4-628SilF0HtHuHdu5EzxD7WRqOrrTIDi_MhEG6_qkNtUK5Wg7KPkofp_VJoF7RS2LhxwEFCO1ICHZlc-o_=s0#w=24&h=24"/>
          </a>
          <div class="scale-media" id="trailer-video-container">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

          </div>
        </div>
      </div>
    </div>


    


    <div class="star-rating" data-score= <%= @avg_rating %> >
    </div>

    <p> <%= "#{@reviews.length} ratings" %> </p>

    <%= link_to "Rate and comment", new_movie_review_path(@movie), class: "btn btn-primary" %>

    <br>
    <%= link_to 'Back', movies_path, class: "btn btn-link" %>
    <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-link" %> 
    <% end %>
    
    <br>


    
  </div>
</div>
<div class="container">
  <div class="row">
    <% if user_signed_in? && current_user.admin? %>
    <div class="col-md-12">
      <%= link_to "Add Similar Movie", new_movie_similarity_path(@movie), class: "btn btn-success space" %>
    </div>
    <% end %>


    <div class="col-md-12">
      <% if @similarities.blank? %>
      <h4 class="text-primary"> No Similar Movies yet. Check later! </h4>

      <% else %>
      <h4 class="commentrating"> Similar Movies </h4>
      <% end %>

    </div>

    <div class="col-md-12">
      <% @similarities.each do |similarity| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row space">
            <div class="col-md-12">
             <div class="voting">

              <%= link_to like_link_path(similarity), method: :put do %>
              <span class="thumbup"> up </span>
              <%= similarity.get_upvotes.size %>
              <% end %>


              <%= link_to dislike_link_path(similarity), method: :put do %>
              <span class="thumbdown"> wn </span>
              <%= similarity.get_downvotes.size %>
              <% end %>

            </div>
          </div>

          <div class="col-md-3">



            <div class="similarimage">
              <%= image_tag similarity.image_url, :width => '100', class: "img-thumbnail" if similarity.image.present? %>
              <div class="similarplaybutton">
                <button type="button" class="playsimilar" data-trailer-youtubei-id="<%= similarity.url %>" data-toggle="modal" data-target="#simtrailer">
                </button>
              </div>
            </div>
          </div>

          <div class="col-md-9">   

            <h4> 

              <%= similarity.name %>
            </h4>
            <p>
              <strong>Star:</strong> 
              <%= similarity.actor %> 
            </p>
            <p> 
              <strong>Why is it similar?</strong> 
              <%= similarity.why %>
              <% if user_signed_in? %>
              <% if (similarity.user == current_user) || (current_user.admin?) %>
              <%= link_to "Edit", edit_movie_similarity_path(@movie, similarity) %> |
              <%= link_to "Delete", movie_similarity_path(@movie, similarity), method: :delete %>
              <% end %>  
              <% end %>

            </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  
  <div class="col-md-12">
    <% if @reviews.blank? %>
    <p class="text-warning"> No ratings yet. Be the first one to rate this page! </p>
    <% else %>
    <table class="table">
      <thead>
        <tr>
         <th class="col-md-3"> </th>
         <th class="col-md-9"> </th>
       </tr>
     </thead>


     <% if user_signed_in? && current_user.admin? %>
     <tbody>
      <% @reviews.each do |review| %>
      <tr>
       <td> 
        <h4>
          <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
        </h4>
        <p> <%= review.created_at.strftime("%-m/%-d/%-y") %> </p>
      </td>
      <td>
        <div class="star-rating" data-score= <%= review.rating %> ></div>
        <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

        <% if user_signed_in? %>
        
        <%= link_to "Edit", edit_movie_review_path(@movie, review) %> |
        <%= link_to "Delete", movie_review_path(@movie, review), method: :delete %> 
        <% if review.publish == false %>
        <%= link_to "Approve", approve_movie_review_path(@movie, review), class: "btn btn-success" %>
        <% end %>
        <% end %>  


      </td>
    </tr>

  </tbody>
  <% end %>
  <% else %>

  <tbody>
    <% @reviews.where(publish: true).each do |review| %>
    <tr>
     <td> 
      <h4>
        <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
      </h4>
      <p> <%= review.created_at.strftime("%-m/%-d/%-y") %> </p>
    </td>
    <td>
      <div class="star-rating" data-score= <%= review.rating %> ></div>
      <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

      <% if user_signed_in? %>
      <% if (review.user == current_user) || (current_user.admin?) %>
      <%= link_to "Edit", edit_movie_review_path(@movie, review) %> |
      <%= link_to "Delete", movie_review_path(@movie, review), method: :delete %>
      <% end %>  
      <% end %>

    </td>
  </tr>
  <% end %>
</tbody>
<% end %>



</table>
<% end %>
</div>
</div>
</div>

<!-- Modal for similar movie trailer -->
<div class="modal" id="simtrailer">
  <div class="modal-dialog">
    <div class="modal-content">
      <a href="#" class="hanging-close" data-dismiss="modal" aria-hidden="true">
        <img src="https://lh5.ggpht.com/v4-628SilF0HtHuHdu5EzxD7WRqOrrTIDi_MhEG6_qkNtUK5Wg7KPkofp_VJoF7RS2LhxwEFCO1ICHZlc-o_=s0#w=24&h=24"/>
      </a>
      <div class="scale-media" id="trailer-video-container1">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
 $('.star-rating').raty({
  path: 'https://s3.amazonaws.com/funkyflick1/stars',
  readOnly: true,
  score: function() {
   return $(this).attr('data-score');
 }
});
</script>   



<script type="text/javascript" charset="utf-8">
  // Pause the video when the modal is closed
  $(document).on('click', '.hanging-close, .modal-backdrop, .modal', function (event) {
  // Remove the src so the player itself gets removed, as this is the only
  // reliable way to ensure the video stops playing in IE
  $("#trailer-video-container").empty();
});
  $(document).on('click', '.hanging-close, .modal-backdrop, .modal', function (event) {
  // Remove the src so the player itself gets removed, as this is the only
  // reliable way to ensure the video stops playing in IE
  $("#trailer-video-container1").empty();
});
  // Start playing the video whenever the trailer modal is opened
  $(document).on('click', '.playtrailer', function (event) {
    var trailerYouTubeId = $(this).attr('data-trailer-youtube-id')
  //var trailerYouTubeId = $('.movietrailer').val()
  var sourceUrl = 'http://www.youtube.com/embed/' + trailerYouTubeId + '?autoplay=1&html5=1';
  $("#trailer-video-container").empty().append($("<iframe></iframe>", {
    'id': 'trailer-video',
    'type': 'text-html',
    'src': sourceUrl,
    'frameborder': 0
  }));
});
  $(document).on('click', '.playsimilar', function (event) {
    var trailerYouTubeId1 = $(this).attr('data-trailer-youtubei-id')
  //var trailerYouTubeId = $('.movietrailer').val()
  var sourceUrl1 = 'http://www.youtube.com/embed/' + trailerYouTubeId1 + '?autoplay=1&html5=1';
  $("#trailer-video-container1").empty().append($("<iframe></iframe>", {
    'id': 'trailer-video',
    'type': 'text-html',
    'src': sourceUrl1,
    'frameborder': 0
  }));
});
  
</script>