config/routes.rb
Rails.application.routes.draw do
  

  

  devise_for :users
  resources :movies do
   collection do
     get 'search'
    end 
  resources :reviews, except: [:show, :index] do
    member do
    get 'approve'
    end
  end
    
    resources :similarities, except: [:show, :index]
  end 

  resources :links do
    member do
      put "like", to: "similarities#upvote"
      put "dislike", to: "similarities#downvote" 
    end
  end    
  

  get 'pages/about'

  get 'pages/contact'

  get 'pages/privacy'
  
  root 'movies#index'
  
  

end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>



<footer class="footer">
   <div class="container">
  
   <div class="footer-links center">
       
       <%= link_to "About", pages_about_path %>
       <%= link_to "Privacy", pages_privacy_path %>
       <%= link_to "Contact", pages_contact_path %>
       
    </div>  

    <div class="social center">    
    <a href="https://twitter.com/FunkyFlickcom"> <img alt="twitter" src="https://s3.amazonaws.com/funkyflick1/twitter.png">
    </a>
    <a href="https://www.facebook.com/funkyflick"> <img alt="twitter" src="https://s3.amazonaws.com/funkyflick1/png-1.png">
    </a>
    <div>
    <p> &copy; 2015 FUNKYFLICK, INC. All rights reserved. </p>
   </div>
  
</footer>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> <%= image_tag "https://s3.amazonaws.com/funkyflick1/logoflick.png", class: "logohead" %> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">



      </ul>

      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-left" do %>
      <p>
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
      </p>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
         <li><%= link_to "Sign up", new_user_registration_path %> </li>
         <li><%= link_to "Log in", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Movies</title>
	<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
<!--Latest compiled and minified jQuery" -->
	
</head>
<body>

	<%= render 'layouts/navbar' %>
	<div class="container">
	<% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %> 

		<%= yield %>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>